### ISSUE TITLE
SIFT AMI Default User Issue (with Fix)

### ISSUE THREAD

**Issue by ekristen** [teamdfir/sift#556]
The current AMIs have a problem with the default user (ubuntu) not existing, but it not being set to `sansforensics` either properly.

To work around this simply add this to your user-data when using the AMI. 

```
#cloud-config
system_info:
  default_user:
    name: sansforensics
```

**Note:** if this issue is closed, that means the **LATEST** AMI has been fixed to default the user to sansforensics.
